
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'LayoutsFooter': typeof import("../components/Layouts/Footer.vue")['default']
    'LayoutsHeader': typeof import("../components/Layouts/Header.vue")['default']
    'ModuleAnasayfaSlider': typeof import("../components/module/AnasayfaSlider.vue")['default']
    'ModuleAnasayfaUrunler': typeof import("../components/module/AnasayfaUrunler.vue")['default']
    'ModuleBanner': typeof import("../components/module/Banner.vue")['default']
    'ModuleProductsListe': typeof import("../components/module/ProductsListe.vue")['default']
    'ModuleResimBaslikAciklama': typeof import("../components/module/ResimBaslikAciklama.vue")['default']
    'ModuleResimliYaziAlani': typeof import("../components/module/ResimliYaziAlani.vue")['default']
    'ModuleUrunlerListe': typeof import("../components/module/UrunlerListe.vue")['default']
    'ModuleAccordion': typeof import("../components/module/accordion.vue")['default']
    'ModuleAdvantage': typeof import("../components/module/advantage.vue")['default']
    'ModuleCarrers': typeof import("../components/module/carrers.vue")['default']
    'ModuleContact': typeof import("../components/module/contact.vue")['default']
    'ModuleExampleListModule': typeof import("../components/module/exampleListModule.vue")['default']
    'ModuleExampleModule': typeof import("../components/module/exampleModule.vue")['default']
    'ModuleForm': typeof import("../components/module/form.vue")['default']
    'ModuleProducts': typeof import("../components/module/products.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtLinkLocale': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'SwitchLocalePathLink': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyLayoutsFooter': typeof import("../components/Layouts/Footer.vue")['default']
    'LazyLayoutsHeader': typeof import("../components/Layouts/Header.vue")['default']
    'LazyModuleAnasayfaSlider': typeof import("../components/module/AnasayfaSlider.vue")['default']
    'LazyModuleAnasayfaUrunler': typeof import("../components/module/AnasayfaUrunler.vue")['default']
    'LazyModuleBanner': typeof import("../components/module/Banner.vue")['default']
    'LazyModuleProductsListe': typeof import("../components/module/ProductsListe.vue")['default']
    'LazyModuleResimBaslikAciklama': typeof import("../components/module/ResimBaslikAciklama.vue")['default']
    'LazyModuleResimliYaziAlani': typeof import("../components/module/ResimliYaziAlani.vue")['default']
    'LazyModuleUrunlerListe': typeof import("../components/module/UrunlerListe.vue")['default']
    'LazyModuleAccordion': typeof import("../components/module/accordion.vue")['default']
    'LazyModuleAdvantage': typeof import("../components/module/advantage.vue")['default']
    'LazyModuleCarrers': typeof import("../components/module/carrers.vue")['default']
    'LazyModuleContact': typeof import("../components/module/contact.vue")['default']
    'LazyModuleExampleListModule': typeof import("../components/module/exampleListModule.vue")['default']
    'LazyModuleExampleModule': typeof import("../components/module/exampleModule.vue")['default']
    'LazyModuleForm': typeof import("../components/module/form.vue")['default']
    'LazyModuleProducts': typeof import("../components/module/products.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtLinkLocale': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'LazySwitchLocalePathLink': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const LayoutsFooter: typeof import("../components/Layouts/Footer.vue")['default']
export const LayoutsHeader: typeof import("../components/Layouts/Header.vue")['default']
export const ModuleAnasayfaSlider: typeof import("../components/module/AnasayfaSlider.vue")['default']
export const ModuleAnasayfaUrunler: typeof import("../components/module/AnasayfaUrunler.vue")['default']
export const ModuleBanner: typeof import("../components/module/Banner.vue")['default']
export const ModuleProductsListe: typeof import("../components/module/ProductsListe.vue")['default']
export const ModuleResimBaslikAciklama: typeof import("../components/module/ResimBaslikAciklama.vue")['default']
export const ModuleResimliYaziAlani: typeof import("../components/module/ResimliYaziAlani.vue")['default']
export const ModuleUrunlerListe: typeof import("../components/module/UrunlerListe.vue")['default']
export const ModuleAccordion: typeof import("../components/module/accordion.vue")['default']
export const ModuleAdvantage: typeof import("../components/module/advantage.vue")['default']
export const ModuleCarrers: typeof import("../components/module/carrers.vue")['default']
export const ModuleContact: typeof import("../components/module/contact.vue")['default']
export const ModuleExampleListModule: typeof import("../components/module/exampleListModule.vue")['default']
export const ModuleExampleModule: typeof import("../components/module/exampleModule.vue")['default']
export const ModuleForm: typeof import("../components/module/form.vue")['default']
export const ModuleProducts: typeof import("../components/module/products.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const SwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyLayoutsFooter: typeof import("../components/Layouts/Footer.vue")['default']
export const LazyLayoutsHeader: typeof import("../components/Layouts/Header.vue")['default']
export const LazyModuleAnasayfaSlider: typeof import("../components/module/AnasayfaSlider.vue")['default']
export const LazyModuleAnasayfaUrunler: typeof import("../components/module/AnasayfaUrunler.vue")['default']
export const LazyModuleBanner: typeof import("../components/module/Banner.vue")['default']
export const LazyModuleProductsListe: typeof import("../components/module/ProductsListe.vue")['default']
export const LazyModuleResimBaslikAciklama: typeof import("../components/module/ResimBaslikAciklama.vue")['default']
export const LazyModuleResimliYaziAlani: typeof import("../components/module/ResimliYaziAlani.vue")['default']
export const LazyModuleUrunlerListe: typeof import("../components/module/UrunlerListe.vue")['default']
export const LazyModuleAccordion: typeof import("../components/module/accordion.vue")['default']
export const LazyModuleAdvantage: typeof import("../components/module/advantage.vue")['default']
export const LazyModuleCarrers: typeof import("../components/module/carrers.vue")['default']
export const LazyModuleContact: typeof import("../components/module/contact.vue")['default']
export const LazyModuleExampleListModule: typeof import("../components/module/exampleListModule.vue")['default']
export const LazyModuleExampleModule: typeof import("../components/module/exampleModule.vue")['default']
export const LazyModuleForm: typeof import("../components/module/form.vue")['default']
export const LazyModuleProducts: typeof import("../components/module/products.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const LazySwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
